owaspJuiceWebsite=http://localhost:3000/#/
browserName=chrome
communBaseApi=http://localhost:3030/#/
//Endpoints
communApiRest=/rest
communApi=/api
//LoginEndpoint
loginEndpoint=/user/login
//RegustrationEndPoint
registrationEndpoint=/Users/
//AddTheCardEndpoint
addCardEndpoint=/Cards/
//BasketEndPoint
basketEndpoint=/basket/{id}
//OrderSummary
orderSummaryEndpoint=/basket/{id}
//UserEndpoint
userEndpoint=
//resycleEndpoint
recycleEndpoint=/Recycles/
//OrderHistoryEndpoint
orderHistoryEndpoint=/order-history
//MyAddressEndpoint
myAddressEndpoint=/Addresss/
//AddItemsToBasketEndpoint
addItemsToBasketEndPoint=/BasketItems/
//ChangePassword
changePasswordEndpoint=user/change-password
addNewAddressEndpoint=/
communAddress=/Addresss
//payementAPi
paymentApi=
//orderCompletionEndpoint
orderCompletionEndpoint=track-order/{orderId}
//orderCompletionValue
pathParameterOrderCompletion="orderId"
username=emailcfcc5@gmail.com
passwordOfUser=amira@123456789A

