owaspJuiceWebsite=http://localhost:3000/#/
browserName=chrome

communBaseApi=http://localhost:3000

//Endpoints
communApiRest=/rest

communApi=/api

//LoginEndpoint
loginEndpoint=/user/login

//RegustrationEndPoint
registrationEndpoint=/Users/


//BasketEndPoint
basketEndpoint=/basket/{id}

//OrderSummary
orderSummaryEndpoint=/basket/{id}
//UserEndpoint
userEndpoint=
//resycleEndpoint
recycleEndpoint=/Recycles/
//OrderHistoryEndpoint
orderHistoryEndpoint=/order-history
//MyAddressEndpoint
myAddressEndpoint=/Addresss
//AddItemsToBasketEndpoint
addItemsToBasketEndPoint=/BasketItems/{id}
//ChangePassword
changePasswordEndpoint=user/change-password
addNewAddressEndpoint=/
communAddress=/Addresss

//payementAPi
paymentApi=
//orderCompletionEndpoint
orderCompletionEndpoint=track-order/{orderId}
//orderCompletionValue
pathParameterOrderCompletion="orderId"

username=rimgammoudi123@gmail.com
passwordOfUser=amira@123456789A

