# This workfLOW created to execute the basketApiTests
name: basketApiRuningTests
on:
  push:
   branches:
     - OWASPbranch
jobs:
  build-and-test:
   name: "second job"
   runs-on: "ubuntu-latest"
   steps:
    - name: "this is jsut a step"
      run: echo "hello hello"
